import Head from 'next/head'
import Script from 'next/script'
import React, { useEffect, useState } from "react";
import Cookies from 'js-cookie';
import styles from '../styles/Home.module.css'

export default function Home() {

  const [displayComponent, setDisplayComponent] = useState(false);
  let optimizelyData;

  useEffect(() => {

    try {

      optimizelyData = window?.optimizely;

      const utils = optimizelyData?.get('utils');
      utils.waitForElement('body').then(function(){

        const dataObject = optimizelyData?.get('data');
        console.log("Optimizely Data", dataObject);

        const visitorData = optimizelyData?.get('visitor');
        console.log("Visitor Data", visitorData);  // Can get by user id here

        const stateData = optimizelyData?.get('state');
        console.log("State Data", stateData);

        const userIdByCookie = Cookies?.get('optimizelyEndUserId');
        console.log("UserIdByCookie", userIdByCookie);

        const experiments = stateData?.getExperimentStates({
          "isActive": true
        });

        console.log("Experiment Data", experiments);
        console.log("Variation Data", experiments?.variation);

        if (experiments
          && Object.keys(experiments).length === 0
          && Object.getPrototypeOf(experiments) === Object.prototype)
        {
          console.log("No ACtive Experiments");
          return;
        }

        const experimentId = process.env.NEXT_PUBLIC_EXPERIMENT_ID;
        const variationId = process.env.NEXT_PUBLIC_VARIATION_TO_BUCKET_ID;
        const bucketedExperimentId = experiments[experimentId]?.variation?.id || 0;

        console.log('experimentId', experimentId)
        console.log('variationId', variationId)
        console.log('bucketedExperimentId', bucketedExperimentId)

        if (bucketedExperimentId === variationId) {
          setDisplayComponent(true);
        }
      });
    } catch(e) {
      console.log("Error Reading Optimizely", e);
    }
  }, [displayComponent]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Script id="opti-script" src="https://cdn.optimizely.com/js/21454571283.js" type="text/javascript" strategy="beforeInteractive" />

      <main className={styles.main}>
        <h1>
          Optimizely Web API Example
        </h1>
        <div>
          {displayComponent && <div>This component is added in code only when the user is bucketed using the API!</div>}
        </div>
      </main>
    </div>
  )
}