import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Script from 'next/script'
import React, { useRef, useEffect, useState } from "react";
import Link from 'next/link'

export default function Home() {
  const listInnerRef = useRef();
  let optimizelyData;

  const addDataToDataLayer = () => {
    const dataLayer = window?.dataLayer;

    const pageView = document.getElementsByTagName("title")[0].innerHTML;

    dataLayer.push({
      'event': 'Pageview',
      'pageTitle': pageView
     });

     addMetricFromDataLayer(pageView)
  }

  // Add an event based on Javascript data
  const addMetricFromDataLayer = (pageView) => {

    console.log('addMetricFromDataLayer', pageView);

    optimizelyData?.push({
      type: "event",
      eventName: "addMetricFromDataLayer",
      tags: {
        pageView
      }
    });
  }

  useEffect(() => {
    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  // Add audience attribute data based on Javascript events
  const handleScroll = () => {

    if (window.scrollY > 900) {
      optimizelyData?.push({
        "type": "user",
        "attributes": {
          "reachedbottom": true
        }
      });
      console.log('Sent Audience')
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <script dangerouslySetInnerHTML={{ __html: `(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','GTM-WGHHHS5');`}}></script>

      </Head>
      {/* Call Opti-Web and set beforeInteractive */}
      <Script id="opti-script" src="https://cdn.optimizely.com/js/21454571283.js" type="text/javascript" strategy="beforeInteractive" />
      <Script id="tag-manager-script" strategy="lazyOnload" src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS}`} />
      <Script id="ga-script" strategy="lazyOnload">
                {`
                    window.dataLayer = window.dataLayer || [];
                    function gtag(){dataLayer.push(arguments);}
                    gtag('js', new Date());
                    gtag('config', '${process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS}', {
                    page_path: window.location.pathname,
                    });
                `}
      </Script>

      <noscript dangerouslySetInnerHTML={{ __html: `<iframe src="https://www.googletagmanager.com/ns.html?id=GTM-WGHHHS5"
      height="0" width="0" style="display:none;visibility:hidden"></iframe>`}}></noscript>

      <div className={styles.container}  onScroll={() => handleScroll()}  ref={listInnerRef} >
        <main className={styles.main}>

          <h3>
            Optimizely Web Sending Custom Events and Segments
          </h3>
          <div>
            Scroll to bottom to trigger a custom segment <br />
            <div  className={styles.buttonBox}>
              <button onClick={() => addDataToDataLayer()} className={styles.button}>
                Add Metric From DataLayer
              </button>
            </div>
          </div>

        </main>
        <footer className={styles.list}>
        </footer>
    </div>
    </>)
}
